# Generated by Django 4.2.3 on 2023-08-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='article',
            name='views_counter',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
