# Generated by Django 4.2.3 on 2023-08-29 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published', 'Can publish products'), ('change_description', 'Can change product description'), ('change_category', 'Can change product category'), ('check_products', 'Can watch their own products')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
