# Generated by Django 4.2.3 on 2023-09-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinf',
            name='phone',
            field=models.CharField(max_length=35, verbose_name='Телефон'),
        ),
    ]
